print("My name is Inayatulla")
print("My age is 22")
print("My city is Tirupathi")
print("My Favorite programming langauge is Python")
print("It is pretty good  python programming language")
print("*")
print("**")
print("***")
print("****")
print("*****")